<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerYO2pY15\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYO2pY15/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYO2pY15.legacy');
=======
if (\class_exists(\ContainerOlesxZJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOlesxZJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOlesxZJ.legacy');
>>>>>>> 1edcc4a9461eb340083b2b1450a4d47044a2ae46

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerYO2pY15\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYO2pY15\App_KernelDevDebugContainer([
    'container.build_hash' => 'YO2pY15',
    'container.build_id' => 'b6051ba8',
    'container.build_time' => 1653993054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYO2pY15');
=======
    \class_alias(\ContainerOlesxZJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOlesxZJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'OlesxZJ',
    'container.build_id' => 'b8bf0222',
    'container.build_time' => 1653992578,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOlesxZJ');
>>>>>>> 1edcc4a9461eb340083b2b1450a4d47044a2ae46
