<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBrecXwn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBrecXwn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBrecXwn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBrecXwn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBrecXwn\App_KernelDevDebugContainer([
    'container.build_hash' => 'BrecXwn',
    'container.build_id' => '8655f9e0',
    'container.build_time' => 1653892074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBrecXwn');
