<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAqmftJH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAqmftJH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAqmftJH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAqmftJH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAqmftJH\App_KernelDevDebugContainer([
    'container.build_hash' => 'AqmftJH',
    'container.build_id' => '3196eca3',
    'container.build_time' => 1654694494,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAqmftJH');
