<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_mainget_all_products' => [[], ['_controller' => 'App\\Controller\\ProductController::getAllProducts'], [], [['text', '/api/products/all']], [], [], []],
    'api_mainfind_a_product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::findProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products/find']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/loginv']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logoutv']], [], [], []],
    'app_home' => [['reactRouting'], ['reactRouting' => null, '_controller' => 'App\\Controller\\SpaController::index'], ['reactRouting' => '(?!api).+'], [['variable', '/', '(?!api).+', 'reactRouting', true]], [], [], []],
];
